/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ImageOptimizeRouteImport } from './routes/image-optimize'
import { Route as ImageFilterRouteImport } from './routes/image-filter'
import { Route as CadRouteImport } from './routes/cad'
import { Route as A11yRouteImport } from './routes/a11y'
import { Route as IndexRouteImport } from './routes/index'
import { Route as A11yScreenReaderRouteImport } from './routes/a11y/screen-reader'
import { Route as A11yModalRouteImport } from './routes/a11y/modal'
import { Route as A11yKeyboardRouteImport } from './routes/a11y/keyboard'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageOptimizeRoute = ImageOptimizeRouteImport.update({
  id: '/image-optimize',
  path: '/image-optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageFilterRoute = ImageFilterRouteImport.update({
  id: '/image-filter',
  path: '/image-filter',
  getParentRoute: () => rootRouteImport,
} as any)
const CadRoute = CadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => rootRouteImport,
} as any)
const A11yRoute = A11yRouteImport.update({
  id: '/a11y',
  path: '/a11y',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const A11yScreenReaderRoute = A11yScreenReaderRouteImport.update({
  id: '/screen-reader',
  path: '/screen-reader',
  getParentRoute: () => A11yRoute,
} as any)
const A11yModalRoute = A11yModalRouteImport.update({
  id: '/modal',
  path: '/modal',
  getParentRoute: () => A11yRoute,
} as any)
const A11yKeyboardRoute = A11yKeyboardRouteImport.update({
  id: '/keyboard',
  path: '/keyboard',
  getParentRoute: () => A11yRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a11y': typeof A11yRouteWithChildren
  '/cad': typeof CadRoute
  '/image-filter': typeof ImageFilterRoute
  '/image-optimize': typeof ImageOptimizeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/a11y/keyboard': typeof A11yKeyboardRoute
  '/a11y/modal': typeof A11yModalRoute
  '/a11y/screen-reader': typeof A11yScreenReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a11y': typeof A11yRouteWithChildren
  '/cad': typeof CadRoute
  '/image-filter': typeof ImageFilterRoute
  '/image-optimize': typeof ImageOptimizeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/a11y/keyboard': typeof A11yKeyboardRoute
  '/a11y/modal': typeof A11yModalRoute
  '/a11y/screen-reader': typeof A11yScreenReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a11y': typeof A11yRouteWithChildren
  '/cad': typeof CadRoute
  '/image-filter': typeof ImageFilterRoute
  '/image-optimize': typeof ImageOptimizeRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/a11y/keyboard': typeof A11yKeyboardRoute
  '/a11y/modal': typeof A11yModalRoute
  '/a11y/screen-reader': typeof A11yScreenReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a11y'
    | '/cad'
    | '/image-filter'
    | '/image-optimize'
    | '/profile'
    | '/projects'
    | '/a11y/keyboard'
    | '/a11y/modal'
    | '/a11y/screen-reader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a11y'
    | '/cad'
    | '/image-filter'
    | '/image-optimize'
    | '/profile'
    | '/projects'
    | '/a11y/keyboard'
    | '/a11y/modal'
    | '/a11y/screen-reader'
  id:
    | '__root__'
    | '/'
    | '/a11y'
    | '/cad'
    | '/image-filter'
    | '/image-optimize'
    | '/profile'
    | '/projects'
    | '/a11y/keyboard'
    | '/a11y/modal'
    | '/a11y/screen-reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A11yRoute: typeof A11yRouteWithChildren
  CadRoute: typeof CadRoute
  ImageFilterRoute: typeof ImageFilterRoute
  ImageOptimizeRoute: typeof ImageOptimizeRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-optimize': {
      id: '/image-optimize'
      path: '/image-optimize'
      fullPath: '/image-optimize'
      preLoaderRoute: typeof ImageOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-filter': {
      id: '/image-filter'
      path: '/image-filter'
      fullPath: '/image-filter'
      preLoaderRoute: typeof ImageFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad': {
      id: '/cad'
      path: '/cad'
      fullPath: '/cad'
      preLoaderRoute: typeof CadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a11y': {
      id: '/a11y'
      path: '/a11y'
      fullPath: '/a11y'
      preLoaderRoute: typeof A11yRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a11y/screen-reader': {
      id: '/a11y/screen-reader'
      path: '/screen-reader'
      fullPath: '/a11y/screen-reader'
      preLoaderRoute: typeof A11yScreenReaderRouteImport
      parentRoute: typeof A11yRoute
    }
    '/a11y/modal': {
      id: '/a11y/modal'
      path: '/modal'
      fullPath: '/a11y/modal'
      preLoaderRoute: typeof A11yModalRouteImport
      parentRoute: typeof A11yRoute
    }
    '/a11y/keyboard': {
      id: '/a11y/keyboard'
      path: '/keyboard'
      fullPath: '/a11y/keyboard'
      preLoaderRoute: typeof A11yKeyboardRouteImport
      parentRoute: typeof A11yRoute
    }
  }
}

interface A11yRouteChildren {
  A11yKeyboardRoute: typeof A11yKeyboardRoute
  A11yModalRoute: typeof A11yModalRoute
  A11yScreenReaderRoute: typeof A11yScreenReaderRoute
}

const A11yRouteChildren: A11yRouteChildren = {
  A11yKeyboardRoute: A11yKeyboardRoute,
  A11yModalRoute: A11yModalRoute,
  A11yScreenReaderRoute: A11yScreenReaderRoute,
}

const A11yRouteWithChildren = A11yRoute._addFileChildren(A11yRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A11yRoute: A11yRouteWithChildren,
  CadRoute: CadRoute,
  ImageFilterRoute: ImageFilterRoute,
  ImageOptimizeRoute: ImageOptimizeRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
